Bodaclick\BDKEnquiryBundle\Document\Enquiry:
  type: document
  collection: enquiries
  fields:
    id:
      id: true
    name:
      type: string
    form:
      type: string

  indexes:
    name:
      keys:
        name: asc
      options:
        unique: true
        safe: true
        sparse: true

  referenceOne:
    about: ~

  referenceMany:
    answers:
      targetDocument: Answer
      mappedBy: enquiry