services:
    bdk.user_asocciation.listener:
        class: Bodaclick\BDKEnquiryBundle\Doctrine\ORM\EventListener\UserAssociationListener
        arguments: [ %bdk.user_class%]
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata}

    bdk.link_about.listener:
        class: Bodaclick\BDKEnquiryBundle\Doctrine\ORM\EventListener\LinkAboutListener
        tags:
            - { name: doctrine.event_listener, event: prePersist}
            - { name: doctrine.event_listener, event: postLoad}
            - { name: doctrine.event_listener, event: postPersist}


    bdk.enquiry.object_manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getManager
