services:
    bdk.enquiry.manager:
        class: Bodaclick\BDKEnquiryBundle\Model\EnquiryManager
        arguments: [ @bdk.enquiry.object_manager]

    bdk.enquiry.service:
        alias: bdk.enquiry.manager
